timeout: 60s
ess:
    bucket_name: "demo2"
    domain_name: "essintra.cloud.cn"
    username: "13CF9596AF252F798"
    password: "YtxrzxIwTfLLwy8Bw21RLhquhbuDYROP" 
jobs:  
  - job_name: '3K'
    username: back
    password: 'ehouse'
    local_path: './'
    targets: 
        # - ip: 10.106.254.1
        #   file_name: HZBA-B01-ACC-N3048A-running-config 
        - ip: 10.0.254.152
          file_name: sw2960-vm-b-confg 
    actions:
        - expect: '>'

        ## 需要使用双引号对 \n 进行转义。 
        - send: "en 5\n"

        - expect: 'Password:'  

        - send: "back\n"


        - expect: 'SW2960-VM-B#'

        - send: "copy running-config scp://cloud@10.99.70.34\n"  

        - expect: '[10.99.70.34]?'

        - send: "\n"

        - expect: '[cloud]?'

        - send: "\n"

        - expect: '?'

        - send: "\n"


        - expect: 'Password:'

        - send: "cloud\n"

        - expect: '#'

        - send: "exit\n"
