global:
  timeout: 10
  ess:
      bucket_url: "demo"
      username: "abc"
      password: "abc" 
jobs:  
  - job_name: '3K'
    user_name: back
    backup_server: 10.99.70.34
    backup_path: /home/cloud/backup
    targets: 
        - ip: 10.0.254.151
          file_name: HZBA-B01-ACC-N3048A-running-config 
        - ip: 10.0.254.152
          file_name: HZBA-B02-ACC-N3048A-running-config 
    actions:
        - expect: ['rsa','Password:'] 
          goto: ['','enterpassword']                     
        
        - send: 'yes'  
          expect: ['Password:']
        
        - label: 'enterpassword'
          send: 'back23433'  
          expect: ['>'] 
          timeout: 5

        - send: 'en 5'  
          expect: ['Password:']

        - send: 'back23433'  
          expect: ['#']

        - send: 'copy run scp://cloud@10.99.70.34/home/cloud/backup'  
          expect: ['Copy complete']

        - label: 'exit'
          send: 'exit'  
